SCR_EntityCatalogMultiList {
 m_eEntityCatalogType ITEM
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{65BD15E14D376B95}" {
   m_sIdentifier "Rifles"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E15E370BA6}" {
   m_sIdentifier "SMGs"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E1A76B4BFB}" {
   m_sIdentifier "Shotguns"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E15D4606C0}" {
   m_sIdentifier "DMRs"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E1ABA8F24C}" {
   m_sIdentifier "MGs"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E0BCD5BF1B}" {
   m_sIdentifier "Standalone Grenade Launchers"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E1BFDFE866}" {
   m_sIdentifier "Launchers"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E187351A1F}" {
   m_sIdentifier "Handguns"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E198F255C1}" {
   m_sIdentifier "Crew Served Weapons"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E18B3EC3C2}" {
   m_sIdentifier "Throwables"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E1908EE53D}" {
   m_sIdentifier "Small Arms Ammunition"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E0B236AAD7}" {
   m_sIdentifier "Underbarrel Ammunition"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E19CBDB80D}" {
   m_sIdentifier "Launcher Ammunition"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E1E00AF5A2}" {
   m_sIdentifier "Crew Served Weapon Ammunition"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E1EDF1F066}" {
   m_sIdentifier "Explosives & Mines"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E1CE2F2BA4}" {
   m_sIdentifier "Binoculars & Watches"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E0563CD18E}" {
   m_sIdentifier "Muzzle Attachments"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E05CAA7052}" {
   m_sIdentifier "Underbarrel Attachments"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E0A377830C}" {
   m_sIdentifier "Lasers & Flashlights"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E0A689C482}" {
   m_sIdentifier "Optics"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E0AA55B465}" {
   m_sIdentifier "Bayonets"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E023D80843}" {
   m_sIdentifier "Common Equipment"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E02AEE77A4}" {
   m_sIdentifier "Medical Equipment"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E02E4F3760}" {
   m_sIdentifier "Special Equipment"
  }
  SCR_EntityCatalogMultiListEntry "{65BD1970B20180F1}" {
   m_sIdentifier "Helmets"
  }
  SCR_EntityCatalogMultiListEntry "{65BD15E0370E232B}" {
   m_sIdentifier "Helmet Attachments"
  }
  SCR_EntityCatalogMultiListEntry "{65BD1970B5C09F3D}" {
   m_sIdentifier "Soft Covers"
  }
  SCR_EntityCatalogMultiListEntry "{65BD1970B5A830B4}" {
   m_sIdentifier "Blouse"
  }
  SCR_EntityCatalogMultiListEntry "{65BD1970B58EB371}" {
   m_sIdentifier "Trousers"
  }
  SCR_EntityCatalogMultiListEntry "{65BD269344DE5613}" {
   m_sIdentifier "Suits"
  }
  SCR_EntityCatalogMultiListEntry "{65BD1970B572E1F0}" {
   m_sIdentifier "Boots"
  }
  SCR_EntityCatalogMultiListEntry "{65BD1970B559C40B}" {
   m_sIdentifier "Handwear"
  }
  SCR_EntityCatalogMultiListEntry "{65BD1970918D8214}" {
   m_sIdentifier "Webbing & Pouches"
  }
  SCR_EntityCatalogMultiListEntry "{65BD19708E218B17}" {
   m_sIdentifier "Vests"
  }
  SCR_EntityCatalogMultiListEntry "{65BD19708EAB7343}" {
   m_sIdentifier "Backpacks"
  }
 }
}