SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 UIInfo SCR_FactionUIInfo "{65831D0ECD5FD60A}" {
  Name "[DO NOT USE]"
  Icon "{84E139FCF774AC44}Assets/UVChecker.edds"
  m_sNameUpper "[DO NOT USE]"
 }
 m_bIsPlayable 0
 m_bShowInWelcomeScreenIfNonPlayable 0
}