SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{550EDE9A99854EAE}" {
   m_Info SCR_UIInfo "{550EDE93E0A8DB6E}" {
    Name "Corbec"
    Icon "{CC785E325DBF98B7}Flags/corbec_BCR.edds"
   }
  }
  SCR_EditableEntityCoreLabelSetting "{65833B5F1E1DA63D}" {
   m_bFilterEnabled 0
  }
 }
}